package top.shaozuo.geektime.java01.week07.dao;

import top.shaozuo.geektime.java01.week07.model.ShopOrder;

public interface ShopOrderMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    int insert(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    int insertSelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    ShopOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    int updateByPrimaryKeySelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    int updateByPrimaryKey(ShopOrder record);
}