package top.shaozuo.geektime.java01.week07.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ShopOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.sn
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.buyer_id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.buyer_username
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String buyerUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.payment_method_code
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String paymentMethodCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.payment_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.shipping_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String shippingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date expire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.lock_expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date lockExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.fee
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.freight
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.tax
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.total_amount
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.amount_payable
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal amountPayable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.amount_paid
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private BigDecimal amountPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.finish_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_time
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_message
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String orderMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.create_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.update_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.remarks
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.del_flag
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.id
     *
     * @return the value of shop_order.id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.id
     *
     * @param id the value for shop_order.id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.sn
     *
     * @return the value of shop_order.sn
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withSn(String sn) {
        this.setSn(sn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.sn
     *
     * @param sn the value for shop_order.sn
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_status
     *
     * @return the value of shop_order.order_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withOrderStatus(String orderStatus) {
        this.setOrderStatus(orderStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_status
     *
     * @param orderStatus the value for shop_order.order_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.buyer_id
     *
     * @return the value of shop_order.buyer_id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withBuyerId(String buyerId) {
        this.setBuyerId(buyerId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.buyer_id
     *
     * @param buyerId the value for shop_order.buyer_id
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.buyer_username
     *
     * @return the value of shop_order.buyer_username
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getBuyerUsername() {
        return buyerUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withBuyerUsername(String buyerUsername) {
        this.setBuyerUsername(buyerUsername);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.buyer_username
     *
     * @param buyerUsername the value for shop_order.buyer_username
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setBuyerUsername(String buyerUsername) {
        this.buyerUsername = buyerUsername == null ? null : buyerUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.payment_method_code
     *
     * @return the value of shop_order.payment_method_code
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getPaymentMethodCode() {
        return paymentMethodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withPaymentMethodCode(String paymentMethodCode) {
        this.setPaymentMethodCode(paymentMethodCode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.payment_method_code
     *
     * @param paymentMethodCode the value for shop_order.payment_method_code
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setPaymentMethodCode(String paymentMethodCode) {
        this.paymentMethodCode = paymentMethodCode == null ? null : paymentMethodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.payment_status
     *
     * @return the value of shop_order.payment_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withPaymentStatus(String paymentStatus) {
        this.setPaymentStatus(paymentStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.payment_status
     *
     * @param paymentStatus the value for shop_order.payment_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus == null ? null : paymentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.shipping_status
     *
     * @return the value of shop_order.shipping_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withShippingStatus(String shippingStatus) {
        this.setShippingStatus(shippingStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.shipping_status
     *
     * @param shippingStatus the value for shop_order.shipping_status
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setShippingStatus(String shippingStatus) {
        this.shippingStatus = shippingStatus == null ? null : shippingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.expire
     *
     * @return the value of shop_order.expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withExpire(Date expire) {
        this.setExpire(expire);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.expire
     *
     * @param expire the value for shop_order.expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.lock_expire
     *
     * @return the value of shop_order.lock_expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getLockExpire() {
        return lockExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withLockExpire(Date lockExpire) {
        this.setLockExpire(lockExpire);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.lock_expire
     *
     * @param lockExpire the value for shop_order.lock_expire
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setLockExpire(Date lockExpire) {
        this.lockExpire = lockExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.fee
     *
     * @return the value of shop_order.fee
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withFee(BigDecimal fee) {
        this.setFee(fee);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.fee
     *
     * @param fee the value for shop_order.fee
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.freight
     *
     * @return the value of shop_order.freight
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withFreight(BigDecimal freight) {
        this.setFreight(freight);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.freight
     *
     * @param freight the value for shop_order.freight
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.tax
     *
     * @return the value of shop_order.tax
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withTax(BigDecimal tax) {
        this.setTax(tax);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.tax
     *
     * @param tax the value for shop_order.tax
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.total_amount
     *
     * @return the value of shop_order.total_amount
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withTotalAmount(BigDecimal totalAmount) {
        this.setTotalAmount(totalAmount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.total_amount
     *
     * @param totalAmount the value for shop_order.total_amount
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.amount_payable
     *
     * @return the value of shop_order.amount_payable
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getAmountPayable() {
        return amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withAmountPayable(BigDecimal amountPayable) {
        this.setAmountPayable(amountPayable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.amount_payable
     *
     * @param amountPayable the value for shop_order.amount_payable
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setAmountPayable(BigDecimal amountPayable) {
        this.amountPayable = amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.amount_paid
     *
     * @return the value of shop_order.amount_paid
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public BigDecimal getAmountPaid() {
        return amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withAmountPaid(BigDecimal amountPaid) {
        this.setAmountPaid(amountPaid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.amount_paid
     *
     * @param amountPaid the value for shop_order.amount_paid
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.finish_date
     *
     * @return the value of shop_order.finish_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withFinishDate(Date finishDate) {
        this.setFinishDate(finishDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.finish_date
     *
     * @param finishDate the value for shop_order.finish_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_time
     *
     * @return the value of shop_order.order_time
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withOrderTime(Date orderTime) {
        this.setOrderTime(orderTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_time
     *
     * @param orderTime the value for shop_order.order_time
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_message
     *
     * @return the value of shop_order.order_message
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getOrderMessage() {
        return orderMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withOrderMessage(String orderMessage) {
        this.setOrderMessage(orderMessage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_message
     *
     * @param orderMessage the value for shop_order.order_message
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setOrderMessage(String orderMessage) {
        this.orderMessage = orderMessage == null ? null : orderMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.create_date
     *
     * @return the value of shop_order.create_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withCreateDate(Date createDate) {
        this.setCreateDate(createDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.create_date
     *
     * @param createDate the value for shop_order.create_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.update_date
     *
     * @return the value of shop_order.update_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withUpdateDate(Date updateDate) {
        this.setUpdateDate(updateDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.update_date
     *
     * @param updateDate the value for shop_order.update_date
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.remarks
     *
     * @return the value of shop_order.remarks
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withRemarks(String remarks) {
        this.setRemarks(remarks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.remarks
     *
     * @param remarks the value for shop_order.remarks
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.del_flag
     *
     * @return the value of shop_order.del_flag
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public ShopOrder withDelFlag(String delFlag) {
        this.setDelFlag(delFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.del_flag
     *
     * @param delFlag the value for shop_order.del_flag
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Sat Mar 06 23:29:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sn=").append(sn);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", buyerId=").append(buyerId);
        sb.append(", buyerUsername=").append(buyerUsername);
        sb.append(", paymentMethodCode=").append(paymentMethodCode);
        sb.append(", paymentStatus=").append(paymentStatus);
        sb.append(", shippingStatus=").append(shippingStatus);
        sb.append(", expire=").append(expire);
        sb.append(", lockExpire=").append(lockExpire);
        sb.append(", fee=").append(fee);
        sb.append(", freight=").append(freight);
        sb.append(", tax=").append(tax);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", amountPayable=").append(amountPayable);
        sb.append(", amountPaid=").append(amountPaid);
        sb.append(", finishDate=").append(finishDate);
        sb.append(", orderTime=").append(orderTime);
        sb.append(", orderMessage=").append(orderMessage);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}